name: pachangapp
description: pachangapp

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  line_icons: ^2.0.0
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  google_nav_bar: ^5.0.6
  sidebarx: ^0.14.0
  collapsible_sidebar: ^2.0.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-LightItalic.ttf
          style: italic
